Facturacion y clientes
daver1419/gestion2017 pull request #5
Opened 2017-05-20 16:39 UTC by ntosco

Creo las tablas Factura y ItemxFactura.

Adiciono datos iniciales a tabla Factura.

2017-05-20 17:21 UTC, daver1419 requested changes
Fijate antes de pushear de hacerte un update de master hacia tu branch asi resolves los conflicos

2017-05-20 17:21 UTC, daver1419 commented on script_creacion_inicial.sql
> +	select cli_id
Aca nico no entiendo como agregas los clientes a la factura, osea cada factura tiene un cliente, pero aca no estas filtrando ni vinculando al cliente que le hicieron efectivamente esa factura, osea incluso nose si al ejecutarlo da una error en el sentido de que fact cli id es un campo y ese select te devuelve una tabla.

2017-05-20 17:21 UTC, daver1419 commented on script_creacion_inicial.sql
> +	select cli_id
no perdon no da error esta bien, pero lo que si falta es la vinculacion del cliente correcto y no ponerle cualquiera

2017-05-21 00:45 UTC, ntosco commented on script_creacion_inicial.sql
> +	select cli_id
Tenias razon David, perdon! 
Ahi lo modifique y commite los nuevos cambios.

2017-05-21 00:46 UTC, ntosco reviewed
ok

2017-05-21 02:21 UTC, daver1419 approved these changes

2017-05-21 02:22 UTC, merged