agrego tabla rendicion
daver1419/gestion2017 pull request #8
Opened 2017-05-25 23:58 UTC by ferhaspert

2017-05-27 18:34 UTC, daver1419 requested changes
esta ok salvo que falta un campo

2017-05-27 18:34 UTC, daver1419 commented on script_creacion_inicial.sql
> +
Acá creo que faltaria el importe total

2017-05-29 15:56 UTC, daver1419 approved these changes

2017-05-29 16:54 UTC, ntosco commented
No falta migrar los datos?

2017-05-29 20:18 UTC, daver1419 commented
Uh pasa que pense que la pull era agregar la tabla y que despues en otro branch migraba, se supone que la pull se crea cuando se termina la tarea

2017-05-29 20:49 UTC, ntosco commented
ah okas, no hay problema!

2017-06-02 01:43 UTC, merged