migracionDeViajes
daver1419/gestion2017 pull request #9
Opened 2017-05-27 21:06 UTC by federicosolomonovici

2017-05-27 21:19 UTC, ntosco requested changes
Comments

2017-05-27 21:19 UTC, ntosco commented on script_creacion_inicial.sql
> +
creo que te conviene poner todo antes del exec GARBAGE.SPMigracion , asi pertenece al procedure.

2017-05-27 21:19 UTC, ntosco commented on script_creacion_inicial.sql
> +
Creo Fede que te falto definir la PRIMARY KEY , por masque "viaje_id" sea identity y not null , definila como primary

2017-05-27 22:41 UTC, federicosolomonovici reviewed
Listo

2017-05-28 20:59 UTC, ntosco approved these changes
Oka con esto

2017-05-29 02:45 UTC, merged